### ISSUE TITLE
Docker repository namespace is stripped when tag is missing

### ISSUE THREAD

**Issue by luckymike** [seatgeek/docker-build-cacher#2]
I created a really basic Dockerfile:

```
FROM kolide/fleet
CMD fleet
```

When I deployed, the build failed because it could not find the image `fleet`. Adding the tag (`kolide/fleet:latest`) succeeded.

**Comment by lorenzo** [comment]
This was fixed as a collateral of upgrading the dockerfile parser library in a branch I was working on already :)
